### ISSUE TITLE
Doesn't Seem to Function

### ISSUE THREAD

**Issue by AzzieDev** [seeshaughnessy/MMM-OneTracker#4]
It worked for a few hours several weeks ago. 

I have 2 packages in my OneTracker account, one is not posting any information, and the other is a normal package.

I continue to see the "Where's my stuff?" message.  I'm tempted to believe that OneTracker is now pushing their paid version for people who don't use the app.

Am I the only one?

EDIT: It works when I removed the bad package. My package never arrived and is an exception.

**Comment by seeshaughnessy** [comment]
Thanks for the update! The only way that I could think to link it to OneTracker is to check if the 'days until delivery' are greater than or equal to 0 (this way it will hide the package if it's already been delivered). However, this can cause some strange issues. Sometimes one tracker will show a strange date, or no date, which causes problems with the MMM-OneTracker check.

**Comment by AzzieDev** [comment]
The problem is that it was the first package, and if additional packages were there, it would hide them all. However, having it as the last package, shows them all.
