### ISSUE TITLE
Is there a way to confirm delivered items don't display?

### ISSUE THREAD

**Issue by wenike** [seeshaughnessy/MMM-OneTracker#5]
Currently, I have 3 active USPS tracking numbers and they are the only ones that the app shows displaying for me. However, the module has a couple of others with status of delivered and being displayed. As additional information, I've had times with no active packages and sometimes previously delivered items will display. It acts like the whatever is holding the data to display doesn't get cleared of old data sometimes.

![Screenshot 2021-06-17 4 47 36 PM](https://user-images.githubusercontent.com/32885613/122471212-fb18a700-cf8c-11eb-8fd3-5b864f9f1e63.png)

**Comment by MacG-DD** [comment]
Why are the delivered packages still displayed on your screen? Unfortunately, when my packages get the status "Delivered" from OneTracker, they disappear from the display after a short time. I see the checkmark only for a few hours. 

Is the dot in the OneTracker app in front of the "Delivered" also green for you?

**Comment by wenike** [comment]
It does go away shortly after being marked delivered. They just reappear randomly at some future date as "delivered". I've got one of those happening now, so showing what it looks like on the app vs on the Mirror.

![Screenshot 2021-08-30 9 07 40 AM](https://user-images.githubusercontent.com/32885613/131344001-2152a565-9308-4e04-bb97-dccc477d4031.png)

![Screenshot 2021-08-30 9 08 08 AM](https://user-images.githubusercontent.com/32885613/131344097-06e092cd-c27e-49bf-bbca-abcc68a3d5c9.png)

As you can see, the Xyzal on my mirror is not active in my OneTracker app and the behavior makes me think something similar to a memory thing or array or something isn't getting cleared out and is randomly being pulled back in.

**Comment by seeshaughnessy** [comment]
Hi @wenike,

I updated the code where there was an issue with it checking to see if a package was delivered. I haven't been able to test it since I haven't seen the same issue, but please let me know if this has fixed anything, or created more problems. Please make sure to update your MMM-OneTracker module.

Thanks,
Chris

**Comment by MacG-DD** [comment]
Today your problem also occurred with me, even after updating the module.

All delivered packages were displayed, except for the one that was last delivered this Monday. I found a remedy in the OneTracker app. There I moved the packages that have been delivered for a long time to the archive. On the iPhone, swipe to the left and select "Archive". "Delete" is also possible, and works of course. 

With this, the packages disappear from the display. Why the last delivered is missing, remains a mystery to me.

**Comment by seeshaughnessy** [comment]
Sorry, I'm not a very experienced programmer, so there's probably an easy fix that I'm not seeing. I tried again to update the logic for filtering out old packages, so feel free to see if it works any better now. I'm hoping to fix this so that it's not a requirement to delete/archive using the app, fingers crossed.

**Comment by MacG-DD** [comment]
Not much has actually changed for me. Delivered packages disappear from the display the next day at the latest. Only sometimes an old package shows up. Like today. The package from August 30 was not moved to the archive in the app. There are also others outside the archive.

![MMM-OneTracker](https://user-images.githubusercontent.com/87946060/135438342-257920d3-2195-4947-8933-6d0f0b1f19ca.png)

**Comment by MacG-DD** [comment]
I think it might have something to do with localization. Today is October 7 we write it here so 07.10.2021 or 7. October. It's the same day, but not the same month at the excess displayed packages. 

![grafik](https://user-images.githubusercontent.com/87946060/136344230-de6ec195-0477-48a3-b2ba-ac5f60d97029.png)

**Comment by seeshaughnessy** [comment]
This makes a lot of sense! I’ll take a look at the spot where I compare dates and see if I can do some troubleshooting. Thanks for your help!

**Comment by seeshaughnessy** [comment]
I reviewed the code and realized that it was checking the difference between the "day" string, and not accounting for the month. I updated the code to get the difference between to Date objects, which should now account for the month as well. Please let me know if the issue continues, or if I've created new bugs in doing this... I hope not!
